export const ERROR_CODES = {
  UNAUTHENTICATED: 'UNAUTHENTICATED',
  FORBIDDEN: 'FORBIDDEN',
  NOT_FOUND: 'NOT_FOUND',
  VALIDATION_FAILED: 'VALIDATION_FAILED',

  CUSTOMER_IDENTITY_REQUIRED: 'CUSTOMER_IDENTITY_REQUIRED',
  CUSTOMER_DUPLICATE: 'CUSTOMER_DUPLICATE',
  CUSTOMER_NOT_FOUND: 'CUSTOMER_NOT_FOUND',

  ADDRESS_NOT_OWNED_BY_CUSTOMER: 'ADDRESS_NOT_OWNED_BY_CUSTOMER',
  INVALID_ASSIGNEE: 'INVALID_ASSIGNEE',
  DO_NOT_SERVICE_BLOCK: 'DO_NOT_SERVICE_BLOCK',

  JOB_NOT_FOUND: 'JOB_NOT_FOUND',
  EVENT_NOT_FOUND: 'EVENT_NOT_FOUND',

  ALREADY_RECURRING: 'ALREADY_RECURRING',
  NOT_RECURRING: 'NOT_RECURRING',
  RECURRENCE_SCOPE_REQUIRES_FUTURE: 'RECURRENCE_SCOPE_REQUIRES_FUTURE',
  OCCURRENCE_DELETED: 'OCCURRENCE_DELETED',
  INVALID_EDIT_SCOPE: 'INVALID_EDIT_SCOPE',
  INVALID_DELETE_SCOPE: 'INVALID_DELETE_SCOPE',
  SERIES_NOT_FOUND: 'SERIES_NOT_FOUND',
  JOB_NOT_SCHEDULED: 'JOB_NOT_SCHEDULED',
  FINISHED_OCCURRENCE_IMMUTABLE: 'FINISHED_OCCURRENCE_IMMUTABLE',

  INVALID_DATE: 'INVALID_DATE',
  INVALID_DATETIME: 'INVALID_DATETIME',
  INVALID_DATE_RANGE: 'INVALID_DATE_RANGE',
  INVALID_TIMEZONE: 'INVALID_TIMEZONE',

  UNSUPPORTED_V1_FIELDS: 'UNSUPPORTED_V1_FIELDS',
  NOT_SUPPORTED_V1: 'NOT_SUPPORTED_V1',

  SERVICE_DUPLICATE: 'SERVICE_DUPLICATE',
  SERVICE_IN_USE: 'SERVICE_IN_USE',

  TEAM_MEMBER_IN_USE: 'TEAM_MEMBER_IN_USE',

  INVOICE_ALREADY_EXISTS: 'INVOICE_ALREADY_EXISTS',
  INVOICE_NOT_DRAFT: 'INVOICE_NOT_DRAFT',
  INVOICE_NOT_DRAFT_CANNOT_REOPEN: 'INVOICE_NOT_DRAFT_CANNOT_REOPEN',

  INTERNAL_ERROR: 'INTERNAL_ERROR',
} as const;

export type ErrorCode = (typeof ERROR_CODES)[keyof typeof ERROR_CODES];

export interface ErrorEnvelope {
  error: {
    code: ErrorCode;
    message: string;
    details?: Record<string, unknown>;
  };
}

export interface ItemEnvelope<T> {
  item: T;
}

export interface ItemsEnvelope<T> {
  items: T[];
  nextCursor?: string | null;
}
